// <auto-generated />
using System;
using EstoqueIncenso.Infrastructure.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EstoqueIncenso.Infrastructure.Migrations
{
    [DbContext(typeof(ContextoBancoDados))]
    partial class ContextoBancoDadosModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EstoqueIncenso.Domain.Entidades.Funcionaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("uq_funcionaria_nome");

                    b.ToTable("funcionarias", (string)null);
                });

            modelBuilder.Entity("EstoqueIncenso.Domain.Entidades.RegistroDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<bool>("Falta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("falta");

                    b.Property<int>("FuncionariaId")
                        .HasColumnType("integer")
                        .HasColumnName("funcionaria_id");

                    b.Property<string>("MotivoFalta")
                        .HasColumnType("text")
                        .HasColumnName("motivo_falta");

                    b.Property<string>("ObservacaoFalta")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao_falta");

                    b.Property<int?>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.HasKey("Id");

                    b.HasIndex("FuncionariaId", "Data")
                        .IsUnique()
                        .HasDatabaseName("uq_registro_funcionaria_data");

                    b.ToTable("registros_diarios", null, t =>
                        {
                            t.HasCheckConstraint("chk_exclusividade", "NOT (quantidade IS NOT NULL AND falta = TRUE)");

                            t.HasCheckConstraint("chk_motivo_quando_falta", "(falta = FALSE AND motivo_falta IS NULL) OR (falta = TRUE AND motivo_falta IS NOT NULL)");

                            t.HasCheckConstraint("chk_obs_quando_outro", "motivo_falta != 'Outro' OR (motivo_falta = 'Outro' AND observacao_falta IS NOT NULL AND observacao_falta != '')");

                            t.HasCheckConstraint("chk_quantidade_positiva", "quantidade >= 0 OR quantidade IS NULL");
                        });
                });

            modelBuilder.Entity("EstoqueIncenso.Domain.Entidades.RegistroDiario", b =>
                {
                    b.HasOne("EstoqueIncenso.Domain.Entidades.Funcionaria", "Funcionaria")
                        .WithMany("Registros")
                        .HasForeignKey("FuncionariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Funcionaria");
                });

            modelBuilder.Entity("EstoqueIncenso.Domain.Entidades.Funcionaria", b =>
                {
                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
